language: ruby
rvm:
  - 2.2

install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
before_script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
script:
  - bundle exec rake test
