language: ruby
sudo: required

bundler_args: --without test --jobs 3 --retry 3
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update

rvm:
  - 2.3.1

install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
before_script:
  - bundle exec rails db:migrate
script:
  - bundle exec rails test
