version: '3.3'
services:
  rd:
    image: redis:3.2
    networks: 
      - hta_network
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
  db:
    image: postgres:9.6
    networks: 
      - hta_network
    deploy:
      mode: replicated
      replicas: 1
  web:
    image: paullj1/hackthearch:latest
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - RAILS_SERVE_STATIC_FILES=enabled
      - LANG=en_US.UTF-8
      - PORT=3000
      - DATABASE_URL=postgresql://postgres@db/postgres
      - REDIS_URL=redis://rd:6379/
      - HOST=localhost
      - SECRET_KEY_BASE=NOTASECRET
    volumes:
      - type: bind
        source: /Users/pj/Documents/workspace/hack-the-arch/
        target: /app
    ports:
      - "3000:3000"
    networks: 
      - hta_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  hta_network:
