version: '3.3'
services:
  rd:
    image: redis:3.2
    networks: 
      - hta_network
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/var/lib/redis/data'
    deploy:
      mode: replicated
      replicas: 1
  db:
    image: postgres:9.6
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks: 
      - hta_network
    deploy:
      mode: replicated
      replicas: 1
  web:
    image: paullj1/hackthearch:latest
    env_file: .env
    volumes:
      - hta:/hta/public/assets
    ports:
      - "3000:3000"
    networks: 
      - hta_network
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - db
      - rd

volumes:
  hta:
  redis:
  postgres:

networks:
  hta_network:
